CREATE USER proxy WITH PASSWORD 'proxypass'; 
CREATE DATABASE proxy WITH OWNER=proxy;
GRANT ALL PRIVILEGES ON DATABASE proxy to proxy;
-- CREATE USER root WITH PASSWORD 'password'; 
-- GRANT ALL PRIVILEGES ON DATABASE proxy to root;
