SELECT * 
FROM GRUPOSf
    INNER JOIN USUARIO on GRUPOS.uid = USUARIO.uid 
    INNER JOIN GRUPO on GRUPOS.gid = GRUPO.gid
    INNER JOIN URIS on GRUPOS.gid = URIS.gid
WHERE USUARIO.UID=1;


SELECT * 
FROM GRUPOS
    INNER JOIN USUARIO on GRUPOS.uid = USUARIO.uid 
    INNER JOIN GRUPO on GRUPOS.gid = GRUPO.gid
    INNER JOIN WORDS on GRUPOS.gid = WORDS.gid
WHERE USUARIO.UID=1;

SELECT * 
FROM GRUPOS
    INNER JOIN USUARIO on GRUPOS.uid = USUARIO.uid 
    INNER JOIN GRUPO on GRUPOS.gid = GRUPO.gid
WHERE USUARIO.UID=1;